import { Response } from "../../types";

export const responsePage1: Response = {
  items: [
    {
      id: "1",
      name: "Software Engineer",
      area: { name: "Moscow" },
      salary: { from: 100000, to: 150000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/1",
      employer: { name: "Company A" },
      experience: { name: "1-3 года" },
    },
    {
      id: "2",
      name: "Data Scientist",
      area: { name: "St. Petersburg" },
      salary: { from: null, to: 180000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/2",
      employer: { name: "Company B" },
      experience: { name: "3-5 лет" },
    },
    {
      id: "3",
      name: "DevOps Engineer",
      area: { name: "Kazan" },
      salary: { from: 90000, to: null, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/3",
      employer: { name: "Company C" },
      experience: { name: "нет опыта" },
    },
    {
      id: "4",
      name: "QA Engineer",
      area: { name: "Novosibirsk" },
      salary: { from: 80000, to: 120000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/4",
      employer: { name: "Company D" },
      experience: { name: "1-2 года" },
    },
    {
      id: "5",
      name: "Frontend Developer",
      area: { name: "Yekaterinburg" },
      salary: { from: 70000, to: 110000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/5",
      employer: { name: "Company E" },
      experience: { name: "нет опыта" },
    },
    {
      id: "6",
      name: "Backend Developer",
      area: { name: "Nizhny Novgorod" },
      salary: { from: 60000, to: 100000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/6",
      employer: { name: "Company F" },
      experience: { name: "2-4 года" },
    },
    {
      id: "7",
      name: "Fullstack Developer",
      area: { name: "Rostov-on-Don" },
      salary: { from: 50000, to: 90000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/7",
      employer: { name: "Company G" },
      experience: { name: "3-6 лет" },
    },
    {
      id: "8",
      name: "UX/UI Designer",
      area: { name: "Krasnodar" },
      salary: { from: 40000, to: 80000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/8",
      employer: { name: "Company H" },
      experience: { name: "нет опыта" },
    },
    {
      id: "9",
      name: "Project Manager",
      area: { name: "Samara" },
      salary: { from: 30000, to: 70000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/9",
      employer: { name: "Company I" },
      experience: { name: "2-5 лет" },
    },
    {
      id: "10",
      name: "Business Analyst",
      area: { name: "Omsk" },
      salary: { from: 20000, to: 60000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/10",
      employer: { name: "Company J" },
      experience: { name: "нет опыта" },
    },
  ],
  pages: 2,
  page: 0,
};
export const responsePage2: Response = {
  items: [
    {
      id: "11",
      name: "IT Consultant",
      area: { name: "Krasnoyarsk" },
      salary: { from: 15000, to: 50000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/11",
      employer: { name: "Company K" },
      experience: { name: "1-3 года" },
    },
    {
      id: "12",
      name: "Network Administrator",
      area: { name: "Irkutsk" },
      salary: { from: 12000, to: 40000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/12",
      employer: { name: "Company L" },
      experience: { name: "2-4 года" },
    },
    {
      id: "13",
      name: "Database Administrator",
      area: { name: "Vladivostok" },
      salary: { from: 10000, to: 30000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/13",
      employer: { name: "Company M" },
      experience: { name: "3-6 лет" },
    },
    {
      id: "14",
      name: "Cybersecurity Specialist",
      area: { name: "Sochi" },
      salary: { from: 15000, to: 50000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/14",
      employer: { name: "Company N" },
      experience: { name: "1-3 года" },
    },
    {
      id: "15",
      name: "Data Analyst",
      area: { name: "Khabarovsk" },
      salary: { from: 10000, to: 30000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/15",
      employer: { name: "Company O" },
      experience: { name: "нет опыта" },
    },
    {
      id: "16",
      name: "Marketing Specialist",
      area: { name: "Tomsk" },
      salary: { from: 8000, to: 20000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/16",
      employer: { name: "Company P" },
      experience: { name: "1-2 года" },
    },
    {
      id: "17",
      name: "Sales Manager",
      area: { name: "Barnaul" },
      salary: { from: 12000, to: 40000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/17",
      employer: { name: "Company Q" },
      experience: { name: "2-4 года" },
    },
    {
      id: "18",
      name: "HR Manager",
      area: { name: "Novokuznetsk" },
      salary: { from: 10000, to: 30000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/18",
      employer: { name: "Company R" },
      experience: { name: "3-6 лет" },
    },
    {
      id: "19",
      name: "Financial Analyst",
      area: { name: "Kemerovo" },
      salary: { from: 15000, to: 50000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/19",
      employer: { name: "Company S" },
      experience: { name: "1-3 года" },
    },
    {
      id: "20",
      name: "Logistics Manager",
      area: { name: "Prokopyevsk" },
      salary: { from: 10000, to: 30000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/20",
      employer: { name: "Company T" },
      experience: { name: "нет опыта" },
    },
  ],
  pages: 2,
  page: 1,
};

export const responseSearchText: Response = {
  items: [
    {
      id: "1",
      name: "Frontend Developer",
      area: { name: "Moscow" },
      salary: { from: 100000, to: 150000, currency: "RUB" },
      alternate_url: "https://example.com/vacancy/1",
      employer: { name: "Company Z" },
      experience: { name: "1-3 года" },
    },
  ],
  pages: 1,
  page: 0,
};
